#server
server.port=9999


#jsp 
spring.mvc.view.suffix=.jsp
spring.mvc.view.prefix=WEB-INF/views/

#database
spring.datasource.url=jdbc:mysql://localhost:3306/projectmgmt26
spring.datasource.username=root
spring.datasource.password=root



#hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ============================
# HikariCP Settings
# ============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
# 5 minutes
spring.datasource.hikari.idle-timeout=300000
# 30 minutes
spring.datasource.hikari.max-lifetime=1800000        
#30 seconds
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=MyHikariPool



